**Gestione Energetica ed Automazione negli Edifici (GEAE) A.A. 2024/2025**

*Tutto il materiale didattico messo a disposizione degli studenti (compresi script, markdown, presentazioni, video e Virtual Classroom) è da utilizzarsi esclusivamente per scopi didattici e nell’ambito del corso di “gestione energetica e automazione negli edifici”. È vietata ogni forma di utilizzo diverso, redistribuzione e pubblicazione on line. Per ogni eventuale dubbio o richiesta contattare il titolare del corso prof. Alfonso Capozzoli a alfonso.capozzoli@polito.it*

# Exercise 1 - Part 2: Introduction to Numpy

### Importing Numpy

In [1]:
import numpy as np

### Creating NumPy Arrays
Creating a 1D array (vector) of temperatures in Celsius

In [2]:
temperatures_celsius = np.array([20, 25, 30, 35, 40])
print("Temperatures in Celsius:", temperatures_celsius)

Temperatures in Celsius: [20 25 30 35 40]


Creating a 2D array (matrix) representing a grid of pressure values

In [3]:
pressures = np.array([
    [1.0, 1.2, 1.4],
    [1.1, 1.3, 1.5],
    [1.2, 1.4, 1.6]
])
print("Pressure grid (bar):\n", pressures)

Pressure grid (bar):
 [[1.  1.2 1.4]
 [1.1 1.3 1.5]
 [1.2 1.4 1.6]]


### Array Operations
Converting temperatures from Celsius to Kelvin

In [4]:
temperatures_kelvin = temperatures_celsius + 273.15
print("Temperatures in Kelvin:", temperatures_kelvin)

Temperatures in Kelvin: [293.15 298.15 303.15 308.15 313.15]


Calculating the average temperature

In [5]:
average_temperature = np.mean(temperatures_celsius)
print("Average temperature (°C):", average_temperature)

Average temperature (°C): 30.0


Performing element-wise multiplication

In [6]:
volumes = np.array([1.0, 1.5, 2.0, 2.5, 3.0])  # in cubic meters
# Calculating the product of pressures and volumes (P*V)
pv_product = pressures[0, 0] * volumes  # Using the first pressure value for simplicity
print("P*V product:", pv_product)


P*V product: [1.  1.5 2.  2.5 3. ]


### Multidimensional Arrays
Creating a 3D array representing energy consumption over time and different units

In [7]:
energy_consumption = np.random.rand(2, 3, 4)  # Random values for demonstration
print("Energy consumption data:\n", energy_consumption)

Energy consumption data:
 [[[0.12247924 0.7865413  0.4915829  0.08602008]
  [0.93864912 0.88723551 0.97559775 0.15794477]
  [0.18343034 0.48066607 0.26998119 0.81388339]]

 [[0.06158287 0.44954503 0.1562408  0.94135357]
  [0.27198635 0.3513866  0.88843777 0.36096384]
  [0.81613803 0.42830857 0.92869505 0.21107959]]]


### Indexing and Slicing
Accessing elements in an array

In [8]:
first_temperature = temperatures_celsius[0]
print("First temperature (°C):", first_temperature)

First temperature (°C): 20


Slicing arrays

In [9]:
subset_temperatures = temperatures_celsius[1:4]
print("Subset of temperatures (°C):", subset_temperatures)

Subset of temperatures (°C): [25 30 35]


Accessing elements in a 2D array

In [10]:
pressure_value = pressures[1, 2]
print("Pressure at position (1,2) (bar):", pressure_value)

Pressure at position (1,2) (bar): 1.5


### Mathematical Functions


In [11]:
radii = np.array([0.05, 0.1, 0.15])  # in meters
areas = np.pi * radii ** 2  # Calculating areas of circles
print("Areas of circles (m^2):", areas)

Areas of circles (m^2): [0.00785398 0.03141593 0.07068583]


### Statistical Functions
Generating a dataset of measured temperatures with random noise

In [12]:
measured_temperatures = temperatures_celsius + np.random.normal(0, 0.5, temperatures_celsius.shape)
print("Measured temperatures (°C):", measured_temperatures)

Measured temperatures (°C): [19.04437072 24.34627217 29.6076911  34.51169174 40.94897854]


Calculating standard deviation

In [13]:
std_dev = np.std(measured_temperatures)
print("Standard deviation of measured temperatures (°C):", std_dev)

Standard deviation of measured temperatures (°C): 7.640744956589269
